AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  bucketName:
    Type: String
  keyToBuildArtefact:
    Type: String
  notificationTopicArn:
    Type: String
  dataBucket:
    Type: String
  sessionDB:
    Type: String
Resources:
  ProfessorAnimalLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.myHandler
      Runtime: nodejs6.10
      # https://github.com/awslabs/serverless-application-model/issues/61
      # https://github.com/awslabs/serverless-application-model/blob/master/HOWTO.md#using-intrinsic-functions
      #CodeUri: !Join [ 's3://', !Ref bucketName, '/professor-animal/src/', !Ref keyToBuildArtefact ]
      CodeUri:
        Bucket: !Ref bucketName
        Key: !Ref keyToBuildArtefact
      MemorySize: 128
      Timeout: 3
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref sessionDB
        - SNSPublishMessagePolicy:
            TopicName: !Ref notificationTopicArn
        - S3ReadPolicy:
            BucketName: !Ref dataBucket
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /apiaiwebhook
            Method: post
            RestApiId: !Ref ProfessorAnimalApi
      Environment:
        Variables:
          NODE_ENV: 'production'
          NOTIFICATION_TOPIC_ARN: !Ref notificationTopicArn

  ProfessorAnimalApi:
    Type: AWS::Serverless::Api
    Properties:
      # can't use DefinitionUri
      # https://github.com/awslabs/serverless-application-model/issues/305
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: !Join [ '', ['s3://', !Ref bucketName, '/professor-animal/deployer/swagger.yml'] ]
      StageName: "dev"

Outputs:
  ProfessorAnimalApi:
    Description: "API Gateway endpoint URL for dev stage for ProfessorAnimalLambdaFunction function"
    Value: !Sub "https://${ProfessorAnimalApi}.execute-api.${AWS::Region}.amazonaws.com/dev/apiaiwebhook/"

# https://github.com/awslabs/serverless-application-model/tree/master/examples/2016-10-31/api_swagger_cors